indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://playback.ru
      name: PlayBack.Ru
    - url: https://https://proselyte.net
      name: Proselyte.net

someParameter: 3322

server:
  port: 8080

spring:
  datasource:
    username: root
    password: 3141
    url: jdbc:mysql://localhost:3306/search_engine2?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

